image:
  repository: ghcr.io/fuseml/fuseml-installer
  pullPolicy: Always
  tag:

# main command to pass to the installer
installerCmd: "install"

# Path (URL) to custom repository with FuseML extensions
extensionsRepository:

# List of extensions to install
extensions: []

# The domain for Fuseml. Should be pointing to the load balancer public IP.
systemDomain:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "fuseml-installer"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
