name: Lint Chart

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart-testing (lint)
        run: .ci/helm-lint.sh
